@startuml classes
set namespaceSeparator none
class "app.gui.calculationsWindow.Ui_metricsWindow" as app.gui.calculationsWindow.Ui_metricsWindow {
  backMainBtn
  classes : int
  exportExcelBtn
  helpBtn_2
  mainWindow
  manualWindow
  metricsTbl
  nocLbl
  projectNameLbl_2
  project_obj
  ui
  window
  backToMain()
  exportToExcel()
  openManual()
  retranslateUi(metricsWindow)
  setupUi(metricsWindow, project_obj, mainWindow)
}
class "app.gui.mainWindow.Ui_MainWindow" as app.gui.mainWindow.Ui_MainWindow {
  calculateBtn
  calculationsWindow
  centralwidget
  file_name : str
  helpBtn
  label
  manualWindow
  nameLbl
  openFolderButton
  pythonProjectLbl
  selectProjectLbl
  selectedProjectLbl
  statusbar
  ui
  window
  calcMetrics()
  openFiles()
  openManual()
  retranslateUi(MainWindow)
  setupUi(MainWindow)
}
class "app.gui.metricsManualWindow.Ui_Dialog" as app.gui.metricsManualWindow.Ui_Dialog {
  ...
  previousWindow
  pushButton
  window
  backToWindow()
  retranslateUi(Dialog)
  setupUi(Dialog, previousWindow)
}
app.gui.calculationsWindow.Ui_metricsWindow --* app.gui.mainWindow.Ui_MainWindow : ui
app.gui.metricsManualWindow.Ui_Dialog --* app.gui.calculationsWindow.Ui_metricsWindow : ui
app.gui.metricsManualWindow.Ui_Dialog --* app.gui.mainWindow.Ui_MainWindow : ui
@enduml
