@startuml app
!pragma useIntermediatePackages false

class app.gui.calculationsWindow.Ui_metricsWindow {
}
class app.src.generator.generate_ast.AstGenerator {
  project_obj: None
}
class app.src.visitors.init_visitor.InitCommonsNodeVisitor {
  python_file: None
  curr_class: None
}
class app.src.metrics.calculator.metrics_calculator.MetricsCalculator {
  class_obj: None
}
class app.src.entities.the_project.Project {
  root_folder_path: None
  project_name: None
  python_files: None
}
class app.gui.metricsManualWindow.Ui_Dialog {
}
class app.gui.mainWindow.Ui_MainWindow {
  window: None
  file_name: None
}
class app.src.entities.class_entity.Class {
  class_name: str
  python_file_obj: None
  class_ast_node: None
  methods: None
  fields: None
  hierarchy: None
  cohesion_category_metrics: None
  complexity_category_metrics: None
  coupling_category_metrics: None
  qmood_category_metrics: None
  size_category_metrics: None
}
class app.src.entities.python_file.PythonFile {
  project_obj: None
  file_name: None
  file_full_path: None
  generated_ast: None
  classes: None
}
class app.src.visitors.cc_visitor.CCNodeVisitor {
  class_obj: None
  cc: None
}
class app.src.visitors.hierarchy_visitor.HierarchyNodeVisitor {
  class_obj: None
  parent_classes_list: None
}
class app.src.visitors.lcom_visitor.LCOMNodeVisitor {
  class_obj: None
  uses_in_method: None
  fields: None
}
class app.src.visitors.loc_counter.LOCNodeVisitor {
  class_obj: None
  lines_of_code: None
}
class app.src.visitors.remote_methods_called_visitor.MethodsCalledNodeVisitor {
  class_obj: None
  called: None
}
class app.src.metrics.categories.cohesion_category.CohesionCategory {
}
class app.src.metrics.categories.complexity_category.ComplexityCategory {
}
class app.src.metrics.categories.coupling_category.CouplingCategory {
}
class app.src.metrics.categories.qmood_category.QMOODCategory {
}
class app.src.metrics.categories.size_category.SizeCategory {
}
class app.src.visitors.class_attr_visitor.ClassAttrNodeVisitor {
  class_obj: None
}
footer Generated by //py2puml//
@enduml
